// Code generated by goplus from sri.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package sri implements Subresource-Integrity-style content hashes
// (sha256/sha384/sha512, base64-encoded), used by direnv to fingerprint the
// contents an .envrc is allowed to load.
//
// Adapted from direnv v2.37.1 pkg/sri (MIT, (c) 2019 zimbatm and contributors).
// Pure; differentially tested against the pinned upstream package.
package sri

import (
	"crypto/sha256"
	"crypto/sha512"
	b64 "encoding/base64"
	"encoding/hex"
	"fmt"
	"hash"
	"io"
	"strings"
)

// Algo is a supported hash algorithm — a closed set expressed as a Go+ enum so
// every consumer must handle all three cases.
//
//goplus:enum Algo
type Algo interface{ isAlgo() }

//goplus:variant (Algo) SHA256
type SHA256 struct{}

func (SHA256) isAlgo() {}

//goplus:variant (Algo) SHA384
type SHA384 struct{}

func (SHA384) isAlgo() {}

//goplus:variant (Algo) SHA512
type SHA512 struct{}

func (SHA512) isAlgo() {}

// AlgoCases selects one handler per Algo variant for Fold.
type AlgoCases[R any] struct {
	SHA256 func() R
	SHA384 func() R
	SHA512 func() R
}

// Fold reduces Algo by one-level case analysis.
func Fold[R any](a Algo, cs AlgoCases[R]) R {
	switch any(a).(type) {
	case SHA256:
		return cs.SHA256()
	case SHA384:
		return cs.SHA384()
	case SHA512:
		return cs.SHA512()
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// AlgoEqOverrides carries optional per-variant hooks for AlgoEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type AlgoEqOverrides struct {
	SHA256 func(x, y SHA256) (eq, handled bool)
	SHA384 func(x, y SHA384) (eq, handled bool)
	SHA512 func(x, y SHA512) (eq, handled bool)
}

// AlgoEqualWith reports structural equality of a and b under ov.
func AlgoEqualWith(a, b Algo, ov AlgoEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case SHA256:
		y, ok := any(b).(SHA256)
		if !ok {
			return false
		}
		if ov.SHA256 != nil {
			if eq, handled := ov.SHA256(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case SHA384:
		y, ok := any(b).(SHA384)
		if !ok {
			return false
		}
		if ov.SHA384 != nil {
			if eq, handled := ov.SHA384(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case SHA512:
		y, ok := any(b).(SHA512)
		if !ok {
			return false
		}
		if ov.SHA512 != nil {
			if eq, handled := ov.SHA512(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// AlgoEqual reports structural equality of a and b.
func AlgoEqual(a, b Algo) bool {
	return AlgoEqualWith(a, b, AlgoEqOverrides{})
}

// name is the SRI wire token for the algorithm ("sha256"/"sha384"/"sha512").
//
//goplus:method (Algo) name
func name(a Algo) string {
	switch any(a).(type) {
	case SHA256:

		return "sha256"
	case SHA384:

		return "sha384"
	case SHA512:

		return "sha512"
	default:
		panic("goplus: impossible enum value in match")
	}
}

var b64Enc = b64.StdEncoding

// Hash is a parsed or computed SRI hash: an algorithm plus its raw digest.
type Hash struct {
	algo string
	sum  []byte
}

// String renders the hash in `<algo>-<base64>` form.
func (h *Hash) String() string {
	return h.algo + "-" + b64Enc.EncodeToString(h.sum)
}

// Hex renders the raw digest as a hex string.
func (h *Hash) Hex() string {
	return hex.EncodeToString(h.sum)
}

// Parse reads an `<algo>-<base64>` SRI string back into a Hash.
func Parse(sriHash string) (*Hash, error) {
	elems := strings.SplitN(sriHash, "-", 2)
	if len(elems) != 2 {
		return nil, fmt.Errorf("sri: not a hash %v", sriHash)
	}

	var algo Algo
	switch elems[0] {
	case "sha256":
		algo = SHA256{}
	case "sha384":
		algo = SHA384{}
	case "sha512":
		algo = SHA512{}
	default:
		return nil, fmt.Errorf("sri: unsupported algo %s", elems[0])
	}

	dbuf := make([]byte, b64Enc.DecodedLen(len(elems[1])))
	n, err := b64Enc.Decode(dbuf, []byte(elems[1]))
	if err != nil {
		return nil, err
	}
	sum := dbuf[:n]

	return &Hash{name(algo), sum}, nil
}

// Writer tees everything written to it into an underlying writer while
// accumulating the SRI digest, which Sum then finalizes.
type Writer struct {
	w    io.Writer
	algo Algo
	h    hash.Hash
}

// NewWriter builds a Writer for the given algorithm. It panics on an
// unsupported algorithm, matching upstream.
func NewWriter(w io.Writer, algo Algo) Writer {
	var h hash.Hash
	switch any(algo).(type) {
	case SHA256:

		h = sha256.New()
	case SHA384:

		h = sha512.New384()
	case SHA512:

		h = sha512.New()
	default:
		panic("goplus: impossible enum value in match")
	}
	return Writer{w, algo, h}
}

// Write forwards b to the underlying writer and, on success, into the digest.
func (w Writer) Write(b []byte) (int, error) {
	n, err := w.w.Write(b)
	if err == nil {
		_, _ = w.h.Write(b)
	}
	return n, err
}

// Sum finalizes and returns the accumulated hash.
func (w Writer) Sum() *Hash {
	sum := w.h.Sum(nil)
	return &Hash{name(w.algo), sum}
}
